import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar"; // Import Navbar component
import { Footer } from "@/components/footer"; // Import Footer component
import { WhatsappButton } from "@/components/whatsapp-button"; // Import WhatsappButton component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FQLabs - Make You Better",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Navbar /> {/* Add Navbar here */}
        <div className="flex-grow">
          {children}
        </div>
        <Footer /> {/* Add Footer here */}
        <WhatsappButton /> {/* Add WhatsappButton here */}
      </body>
    </html>
  );
}